export const ADMIN_ACTIONS = {
    FETCH_ALL_USER: 'FETCH_ALL_USER',
    SET_ALL_USER: 'SET_ALL_USER',
    FETCH_APPROVED_ARTICLE: 'FETCH_APPROVED_ARTICLE',
    SET_APPROVED_ARTICLE: 'SET_APPROVED_ARTICLE'
}