export const ADMIN_ACTIONS = {
    FETCH_ALL_USER: 'FETCH_ALL_USER',
    SET_ALL_USER: 'SET_ALL_USER',
    FETCH_APPROVED_ARTICLE: 'FETCH_APPROVED_ARTICLE',
    SET_APPROVED_ARTICLE: 'SET_APPROVED_ARTICLE',
    FETCH_NEW_ARTICLE: 'FETCH_NEW_ARTICLE',
    FETCH_ARTICLES_BY_LOCATION: 'FETCH_ARTICLES_BY_LOCATION',
    SET_NEW_ARTICLE: 'SET_NEW_ARTICLE',  
    FETCH_MODIFIED_ARTICLE: 'FETCH_MODIFIED_ARTICLE',
    SET_MODIFIED_ARTICLE: 'SET_MODIFIED_ARTICLE',
    DELETE_USER: 'DELETE_USER',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    APPROVED_ARTICLE: 'APPROVED_ARTICLE',
    REJECTED_ARTICLE: 'REJECTED_ARTICLE',
    SET_USER_TYPE: 'SET_USER_TYPE',
    DELETE_TARGET_ARTICLE: 'DELETE_TARGET_ARTICLE',
}

