export const ARTICLE_ACTIONS = {
    FETCH_ARTICLES: 'FETCH_ARTICLES',
    FETCH_USER_ARTICLES: 'FETCH_USER_ARTICLES',
    SHOW_ARTICLES: 'SHOW_ARTICLES',
    POST_ARTICLE: 'POST_ARTICLES',
    UPDATE_ARTICLE: 'UPDATE_ARTICLE',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    FETCH_RESEARCH_TYPE: 'FETCH_RESEARCH_TYPE',
    SHOW_RESEARCH_TYPE: 'SHOW_RESEARCH_TYPE',
    FETCH_RESEARCH_PHASE: 'FETCH_RESEARCH_PHASE',
    SHOW_RESEARCH_PHASE: 'SHOW_RESEARCH_PHASE',
}