export const ARTICLE_ACTIONS = {
    FETCH_ARTICLES: 'FETCH_ARTICLES',
    SHOW_ARTICLES: 'SHOW_ARTICLES',
    POST_ARTICLE: 'POST_ARTICLES',
    UPDATE_ARTICLE: 'UPDATE_ARTICLE',
    DELETE_ARTICLE: 'DELETE_ARTICLE'
}