export const RESOURCE_ACTIONS = {
    FETCH_RESOURCES: 'FETCH_RESOURCES',
    SHOW_RESOURCES: 'SHOW_RESOURCES',
    POST_RESOURCE: 'POST_RESOURCES',
    UPDATE_RESOURCE: 'UPDATE_RESOURCE',
    DELETE_RESOURCE: 'DELETE_RESOURCE'
}